# Generated by Django 3.0.7 on 2020-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0002_auto_20200603_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='cake_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cake',
            name='cake_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
