# Generated by Django 3.0.7 on 2020-06-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cakes', '0003_auto_20200608_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='cake_avatar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
